/**
 * Fork-only. Draws the Shorthand mark and writes it to
 * `src/shorthand/brand/mark.svg`.
 *
 * The mark is a lowercase "s" written with a pointed pen: one continuous
 * stroke whose width swells through each bowl and thins to a point at the
 * entry, the waist and the exit. SVG cannot vary stroke-width along a path,
 * so the visible shape has to be an *outline* — the spine offset to both
 * sides by a width profile. Hand-authoring that outline means hand-editing
 * ~200 coordinates every time the curve moves, so it is generated here
 * instead and the curve itself stays editable as the five cubics below.
 *
 * Run: `bun scripts/gen-brand-mark.ts`
 */

type P = readonly [number, number];

/** Spine of the "s", as end-to-end cubic segments on a 64x64 grid. */
const SPINE: readonly (readonly [P, P, P, P])[] = [
  [
    [47, 18],
    [37, 10],
    [20, 14],
    [23, 25],
  ],
  [
    [23, 25],
    [25, 32],
    [43, 34],
    [44, 44],
  ],
  [
    [44, 44],
    [45, 54],
    [29, 59],
    [16, 52],
  ],
];

/**
 * Half-width of the stroke at fractions of its length. A pointed pen lays
 * down ink on the down-strokes and lifts on the joins, so the two bowls are
 * the widest points and the waist between them is nearly hairline.
 */
const WIDTH_PROFILE: readonly (readonly [number, number])[] = [
  [0.0, 0.6],
  [0.24, 5.4],
  [0.5, 2.1],
  [0.76, 5.6],
  [1.0, 0.5],
];

const SAMPLES = 96;

function cubic([p0, p1, p2, p3]: readonly [P, P, P, P], t: number): P {
  const u = 1 - t;
  const a = u * u * u;
  const b = 3 * u * u * t;
  const c = 3 * u * t * t;
  const d = t * t * t;
  return [
    a * p0[0] + b * p1[0] + c * p2[0] + d * p3[0],
    a * p0[1] + b * p1[1] + c * p2[1] + d * p3[1],
  ];
}

function cubicTangent([p0, p1, p2, p3]: readonly [P, P, P, P], t: number): P {
  const u = 1 - t;
  const a = 3 * u * u;
  const b = 6 * u * t;
  const c = 3 * t * t;
  return [
    a * (p1[0] - p0[0]) + b * (p2[0] - p1[0]) + c * (p3[0] - p2[0]),
    a * (p1[1] - p0[1]) + b * (p2[1] - p1[1]) + c * (p3[1] - p2[1]),
  ];
}

function smoothstep(x: number): number {
  return x * x * (3 - 2 * x);
}

function halfWidth(t: number): number {
  for (let i = 1; i < WIDTH_PROFILE.length; i++) {
    const [t0, w0] = WIDTH_PROFILE[i - 1];
    const [t1, w1] = WIDTH_PROFILE[i];
    if (t <= t1) {
      const k = smoothstep((t - t0) / (t1 - t0));
      return w0 + (w1 - w0) * k;
    }
  }
  return WIDTH_PROFILE[WIDTH_PROFILE.length - 1][1];
}

const left: P[] = [];
const right: P[] = [];

for (let i = 0; i <= SAMPLES; i++) {
  const t = i / SAMPLES;
  // Map the global t onto (segment, local t). The segments are close enough in
  // arc length that treating them as equal thirds keeps the profile symmetric.
  const scaled = Math.min(t * SPINE.length, SPINE.length - 1e-9);
  const seg = SPINE[Math.floor(scaled)];
  const local = scaled - Math.floor(scaled);

  const [x, y] = cubic(seg, local);
  const [dx, dy] = cubicTangent(seg, local);
  const len = Math.hypot(dx, dy) || 1;
  const nx = -dy / len;
  const ny = dx / len;
  const w = halfWidth(t);

  left.push([x + nx * w, y + ny * w]);
  right.push([x - nx * w, y - ny * w]);
}

// Fit the drawn glyph to the viewBox. The spine above is authored by eye, so
// its bounds drift every time a control point moves; without this the mark
// sits off-centre in its box and every consumer has to compensate with
// padding, which then goes stale the next time the curve is edited.
const outline: P[] = [...left, ...right.reverse()];
const xs = outline.map((p) => p[0]);
const ys = outline.map((p) => p[1]);
const minX = Math.min(...xs);
const maxX = Math.max(...xs);
const minY = Math.min(...ys);
const maxY = Math.max(...ys);

const PAD = 3;
const scale = (64 - PAD * 2) / Math.max(maxX - minX, maxY - minY);
const offX = PAD + (64 - PAD * 2 - (maxX - minX) * scale) / 2;
const offY = PAD + (64 - PAD * 2 - (maxY - minY) * scale) / 2;
const place = (p: P): P => [
  offX + (p[0] - minX) * scale,
  offY + (p[1] - minY) * scale,
];

const fmt = (p: P) => {
  const q = place(p);
  return `${q[0].toFixed(2)} ${q[1].toFixed(2)}`;
};
const d = [
  `M${fmt(outline[0])}`,
  ...outline.slice(1).map((p) => `L${fmt(p)}`),
  "Z",
].join("");

const svg = `<!-- Generated by scripts/gen-brand-mark.ts - do not edit by hand. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none">
  <path d="${d}" fill="currentColor" />
</svg>
`;

const ts = `// Generated by scripts/gen-brand-mark.ts - do not edit by hand.
// Run \`bun scripts/gen-brand-mark.ts\` after changing the spine or the width
// profile in that script.

/** The Shorthand mark, as a filled outline on a 64x64 viewBox. */
export const MARK_PATH =
  "${d}";
`;

await Bun.write("src/shorthand/brand/mark.svg", svg);
await Bun.write("src/shorthand/brand/mark.generated.ts", ts);
console.log(
  `wrote mark.svg + mark.generated.ts (${d.length} chars of path data)`,
);
